apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "gimme.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gimme.name" . }}
    helm.sh/chart: {{ include "gimme.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gimme.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gimme.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
          - name: GIMME_ENV
            value: {{ .Values.env.gimme_env | default "dev" }}

          - name: GIMME_ALLOWED_GSUITE_DOMAINS
            value: {{ .Values.env.allowed_gsuite_domains }}

          - name: FLASK_ENV
            value: {{ .Values.env.flask_env | default "development"}}

          - name: FLASK_APP
            value: {{ .Values.env.flask_app | default "autoapp.py" }}

          - name: GOOGLE_OAUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.google_oauth_secret_name }}
                key: GOOGLE_OAUTH_CLIENT_ID

          - name: GOOGLE_OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.google_oauth_secret_name }}
                key: GOOGLE_OAUTH_CLIENT_SECRET

          {{- if .Values.extraEnvs }}
{{ toYaml .Values.extraEnvs | indent 10 }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
